version: "3"
services:
   db:
     image: postgres:9.6
     restart: always
     environment:
       POSTGRES_PASSWORD: ${PASS_DB}
       POSTGRES_DB: ${DB_NAME}
     ports:
       - 5435:5432
     volumes:
       - ./postgres-data:/bitnami/postgresql/data